### PR TITLE
Fixed issues when moving to rails 3.1

### PR DESCRIPTION
**Pull request by devigned**
To get the specs passing within 3.1.1 I needed to added in the yajl engine, and a require to ActiveSupport core extensions to fix issue: https://github.com/CompanyBook/massive_record/issues/42. There was also an issue with the notifier dying in the database cleaner.

The specs are passing with the changes.

Comment:
Fixed the issues with the spec passing for 3.1. Added in yajl to the gemspec. Updated the database cleaner to make sure there is a notifier for the instrumenter when data needs to be cleaned up.

### CODE REVIEW

**Comment by thhermansen** [comment]
Goodie :-) I'll try and look at this when I got the time; maybe in the weekend.

**Comment by vincentp** [comment]
hey, great commit :) have you checked the backward compatibility with Rails 3.0.X project?

**Comment by devigned** [comment]
I have not verified backward compatibility with Rails 3.0.X. I'm betting it doesn't currently.

**Comment by devigned** [comment]
I spent some time comparing the performance of massvie record to mongoid, and found a sizable performance hit with massive record. I think this had much to do with the reading and writing of attributes, and caching of known types. There was also significant speed improvements for caching the schema for a given type. With these two changes I was able to see significant improvements.

I also needed to update a few of the specs to use the non-mocked connection spec setup.

I still have not verified backward compatibility. I will take this up shortly.

**Pull request closed without merging**
